---
title: "Two-Way-Plot"
output: html_document
date: "2024-10-21"
---

```{r}
# Sample data
x <- c(1, 2, 3, 4, 5)
y <- c(5, 4, 3, 2, 1)

# Create a two-way dot chart
plot(x, y, main="Two-Way Dot Chart", xlab="Variable X", ylab="Variable Y")
```
```{r}
hair_eye_data <- matrix(c(20, 15, 12,
                          10, 13, 10,
                          15, 14, 13), 
                        nrow = 3, byrow = TRUE,
                        dimnames = list(c("Black", "Brown", "White"),
                                        c("Brown", "Blue", "Blunete")))

# Flatten to long format
flat_data <- as.data.frame(as.table(hair_eye_data))


dotchart(flat_data$Freq, 
         labels=paste(flat_data$Var1, flat_data$Var2, sep="/"),
         main="Dot Chart of Hair/Eye Combinations",
         xlab="Number of Individuals", 
         ylab="Hair/Eye Combination",
         pch=19,              
         col=c("blue", "green", "purple", "red", "orange", "pink", "cyan", "darkgreen", "brown"),
         cex=1.2,         
         cex.lab=1.2,   
         cex.main=1.2,
         lcolor="gray90", 
         font.main=2
         )

```

```{r}

#https://r-coder.com/dot-plot-r/

month <- month.name
expected <- c(15, 16, 20, 31, 11, 6,
              17, 22, 32, 12, 19, 20)
sold <- c(8, 18, 12, 10, 41, 2,
          19, 26, 14, 16, 9, 13)
quarter <- c(rep(1, 3), rep(2, 3), rep(3, 3), rep(4, 3))

data <- data.frame(month, expected, sold, quarter)
data
```
```{r}
dotchart(data$sold, 
         labels = data$month, 
         pch = 21, 
         bg = "green", 
         pt.cex = 1.5, 
         xlab = "Expected sales")

```



```{r}
# Groups
colors <- numeric(4)
colors[quarter == "1"] <- "red"
colors[quarter == "2"] <- "blue"
colors[quarter == "3"] <- "green"
colors[quarter == "4"] <- "orange"

dotchart(data$expected, 
         labels = data$month, 
         pch = 19,
         pt.cex = 1.5, 
         groups = rev(data$quarter), 
         color = colors,
         xlab = "Expected Sales by Quarter")
```
```{r}
haireye <- matrix(data=c(20,84,17,94,5,29,14,16,15,54,
                14,10,68,119,26,7),
                nrow=4,
                ncol=4,
                byrow=TRUE,
                dimnames=list(c("Blue","Green","Hazel","Brown"),
                c("Black","Brunette","Red","Blond"))
                )
haireye
```



```{r}
require(lattice)

trellis.device(color=FALSE)
graphics.off()

windows(width=4.5,height=2.5,pointsize=12)
par(fin=c(4.45,2.45),pin=c(4.45,2.45),
mai=c(0.85,0.85,0.25,0.25))

trellis.par.set("color",TRUE)

figure<-dotplot(haireye,xlab="Frequency",
                ylab="Eye Color",
                as.table=TRUE,
                xlim=c(0,140),
                groups=FALSE,
                stack=FALSE,
                layout=c(4,1),
                col.line="black",
                lty="dotted",
                lwd=1,
                scales=list(alternating=3)
                )

print(figure)
```

```{r}
require(ggplot2)

graphics.off()
windows(width=4.5,height=2.0)

haireye<-matrix(data=c(7,10,16,94,26,14, 14,17,119,54,29,84,68,15,5,20),
                nrow=4,ncol=4,
                byrow=TRUE,
                dimnames=list(c("Blond", "Red","Brunette","Black"),
                         c("Brown","Hazel","Green","Blue"))
              )

haircol<-unlist(dimnames(haireye)[1])
eyecol<-unlist(dimnames(haireye)[2])

hair<-rep(" ",16)
eye<-rep(" ",16)
freq<-rep(0,16)
n=0
for (i in 1:4){ for (j in 1:4){
n<-n+1
hair[n]<-haircol[i]
eye[n]<-eyecol[j]
freq[n]<-haireye[i,j]
}}

hair<-factor(hair,levels=rev(haircol),ordered=TRUE)
eye<-factor(eye,levels=rev(eyecol),ordered=TRUE)

haireyef<-data.frame(hair=hair,eye=eye,freq=freq)

figure<-ggplot(haireyef,aes(x=eye,y=freq)) +
        geom_pointrange(ymin=0,ymax=120,linetype=3) +
        facet_grid( hair)+
        labs(x="Eye Color",y="Frequency") +
        theme(panel.grid=element_blank()) +
        coord_flip()

print(figure)
```


```{r}
flattened_data = as.data.frame(as.table(haireye))
flattened_data
```




```{r}
flattened_data = as.data.frame(as.table(haireye))

dotchart(flattened_data$Freq, 
         labels=paste(flattened_data$Var1, flattened_data$Var2, sep="/"),
         main="Dot Chart of Hair/Eye Combinations",
         xlab="Number of Individuals", 
         ylab="Hair/Eye Combination",
         pch=19,              
         col=c("blue", "green", "purple", "red", 
               "orange", "pink", "cyan", "darkgreen", 
               "brown", "skyblue", "salmon3", "violet",
               "purple", "rosybrown", "maroon", "magenta"),
         cex=1.2,         
         cex.lab=1.2,   
         cex.main=1.2,
         lcolor="gray90", 
         font.main=2
         )
```

```{r}

flattened_data <- as.data.frame(as.table(haireye))


flattened_data <- flattened_data[order(flattened_data$Freq, decreasing = FALSE), ]


dotchart(flattened_data$Freq, 
         labels=paste(flattened_data$Var1, flattened_data$Var2, sep="/"),
         main="Dot Chart of Hair/Eye Combinations",
         xlab="Number of Individuals", 
         ylab="Hair/Eye Combination",
         pch=19,              
         col=c("blue", "green", "purple", "red", 
               "orange", "pink", "cyan", "darkgreen", 
               "brown", "skyblue", "salmon3", "violet",
               "purple", "rosybrown", "maroon", "magenta"),
         cex=1.2,         
         cex.lab=1.2,   
         cex.main=1.2,
         lcolor="gray90", 
         font.main=2
)
```



```{r}
require(ggplot2)


flattened_data$Combination <- paste(flattened_data$Var1, flattened_data$Var2, sep="/")

# Create the ggplot2 dot chart
ggplot(flattened_data, aes(x=Freq, y=reorder(Combination, Freq))) + 
                      geom_point(aes(color=Combination), size=4) +  
    scale_color_manual(values=c("blue", "green", "purple", "red", 
               "orange", "pink", "cyan", "darkgreen", 
               "brown", "skyblue", "salmon3", "violet",
                   "purple", "rosybrown", "maroon", "magenta")) + 
          labs(title="Dot Chart of Hair/Eye Combinations", 
               x="Number of Individuals", 
               y="Hair/Eye Combination") + 
        theme_minimal() +  
        theme(
          plot.title = element_text(size=14, face="bold"),
          axis.title.x = element_text(size=12),  
          axis.title.y = element_text(size=12),  
          axis.text.y = element_text(size=10),
          panel.grid.major = element_line(color="gray90")
  )
```
```{r}
haireye<-matrix(data=c(20,84,17,94,5,29,14,16,15,54,14,10,68,119,26,7),
                    nrow=4,
                    ncol=4,
                    byrow=TRUE,
                    dimnames=list(c("Blue","Green","Hazel","Brown"),
                    c("Black","Brunette","Red","Blond")))
figure<-dotplot(haireye,xlab="Frequency",
                ylab="Eye Color",
                as.table=TRUE,
                groups=FALSE,
                stack=FALSE,
                layout=c(1,4),
                scales=list(alternating=3))
print(figure)
```

